# Generated by Django 2.2 on 2020-02-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentby',
            options={'verbose_name_plural': 'Studentbyer'},
        ),
    ]
