# Generated by Django 3.0.2 on 2020-03-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentby', '0002_auto_20200227_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentby',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
