# Generated by Django 2.2 on 2020-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentby', '0003_auto_20200320_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentby',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
