# Generated by Django 2.2 on 2020-02-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiv', '0003_auto_20200227_1058'),
        ('vaskelister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaskeliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kollektiv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kollektiv.kollektiv')),
            ],
            options={
                'verbose_name_plural': 'Vaskelister',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='vaskeliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaskelister.Vaskeliste'),
        ),
    ]
