# Generated by Django 2.2 on 2020-02-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0002_auto_20200227_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vaskeliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaskelister.Vaskeliste', unique=True),
        ),
    ]
