# Generated by Django 3.0.2 on 2020-03-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0004_auto_20200227_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaskeliste',
            name='kollektiv',
        ),
    ]
