# Generated by Django 2.2 on 2020-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0005_remove_vaskeliste_kollektiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaskeliste',
            name='date',
            field=models.TextField(default=0),
        ),
    ]
