# Generated by Django 2.2 on 2020-03-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0006_vaskeliste_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaskeliste',
            old_name='date',
            new_name='week',
        ),
    ]
