# Generated by Django 2.2 on 2020-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0008_auto_20200323_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaskeliste',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
