# Generated by Django 2.2 on 2020-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0009_vaskeliste_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaskeliste',
            name='name',
            field=models.CharField(default='Ukjent', max_length=20),
        ),
    ]
