# Generated by Django 2.2 on 2020-04-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0010_auto_20200402_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vaskeliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaskelister.Vaskeliste'),
        ),
    ]
