# Generated by Django 2.2 on 2020-04-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0011_auto_20200413_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vaskeliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaskelister.Vaskeliste'),
        ),
    ]
