# Generated by Django 3.0.3 on 2020-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bruker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brukernavn', models.CharField(max_length=30)),
                ('isManager', models.BooleanField()),
            ],
        ),
    ]
