# Generated by Django 3.0.3 on 2020-02-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bruker', '0001_initial'),
        ('kollektiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruker',
            name='kollektiv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kollektiv.kollektiv'),
        ),
    ]
