# Generated by Django 2.2 on 2020-02-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bruker', '0002_bruker_kollektiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='kollektiv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kollektiv.kollektiv'),
        ),
    ]
