# Generated by Django 2.2 on 2020-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruker', '0003_auto_20200225_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruker',
            name='passord',
            field=models.CharField(default='passord', max_length=30),
        ),
    ]
