# Generated by Django 2.2 on 2020-02-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruker', '0004_bruker_passord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='brukernavn',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
