# Generated by Django 2.2 on 2020-02-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruker', '0005_auto_20200226_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bruker',
            options={'verbose_name_plural': 'Brukere'},
        ),
    ]
