# Generated by Django 2.2 on 2020-02-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kollektiv',
            name='kollektivNr',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='kollektiv',
            constraint=models.UniqueConstraint(fields=('kollektivNr', 'studentby'), name='unique_kollektiv'),
        ),
    ]
