# Generated by Django 2.2 on 2020-02-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiv', '0002_auto_20200225_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kollektiv',
            options={'verbose_name_plural': 'Kollektiv'},
        ),
    ]
