# Generated by Django 3.0.2 on 2020-03-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaskelister', '0005_remove_vaskeliste_kollektiv'),
        ('kollektiv', '0003_auto_20200227_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollektiv',
            name='vaskeliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaskelister.Vaskeliste'),
        ),
    ]
